name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - main-mlflow
  pull_request:
    branches:
      - main
      - main-mlflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        run: |
          pytest -v
      - name : Deploy to heroku 

      - name: Run flake8
        run: |
          flake8 .
        env:
          HEROKU_API_TOKEN : ${{secrets.HEROKU_API_TOKEN}}
          HEROKU_API_NAME : ${{secrets.HEROKU_API_NAME}}
        if : github.ref == 'refs/heads/main-mlflow' && job.status == 'sucess'
        run :
          git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heoku.com/$HEROKU_APP_NAME.git
          git push heroku HEAD:main -f